
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from warnings import catch_warnings
with catch_warnings(record=True):
    import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "edb71fda022c6a155717e7a25679040ee0476639",
 "version": "0.23.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
