# This file is MACHINE GENERATED! Do not edit.
# Generated by: tensorflow/python/tools/api/generator/create_python_api.py script.
"""Sparse Tensor Representation.

See also `tf.SparseTensor`.

"""

from __future__ import print_function as _print_function

from tensorflow.python import SparseConditionalAccumulator
from tensorflow.python import SparseTensor
from tensorflow.python import sparse_add_v2 as add
from tensorflow.python import sparse_concat_v2 as concat
from tensorflow.python import sparse_cross as cross
from tensorflow.python import sparse_cross_hashed as cross_hashed
from tensorflow.python import sparse_expand_dims as expand_dims
from tensorflow.python import sparse_eye as eye
from tensorflow.python import sparse_fill_empty_rows as fill_empty_rows
from tensorflow.python import sparse_mask as mask
from tensorflow.python import sparse_maximum as maximum
from tensorflow.python import sparse_minimum as minimum
from tensorflow.python import sparse_reduce_max_v2 as reduce_max
from tensorflow.python import sparse_reduce_sum_v2 as reduce_sum
from tensorflow.python import sparse_reorder as reorder
from tensorflow.python import sparse_reset_shape as reset_shape
from tensorflow.python import sparse_reshape as reshape
from tensorflow.python import sparse_retain as retain
from tensorflow.python import sparse_segment_mean_v2 as segment_mean
from tensorflow.python import sparse_segment_sqrt_n_v2 as segment_sqrt_n
from tensorflow.python import sparse_segment_sum_v2 as segment_sum
from tensorflow.python import sparse_slice as slice
from tensorflow.python import sparse_softmax as softmax
from tensorflow.python import sparse_split_v2 as split
from tensorflow.python import sparse_tensor_dense_matmul as sparse_dense_matmul
from tensorflow.python import sparse_tensor_to_dense as to_dense
from tensorflow.python import sparse_to_indicator as to_indicator
from tensorflow.python import sparse_transpose as transpose

del _print_function
