# This file is MACHINE GENERATED! Do not edit.
# Generated by: tensorflow/python/tools/api/generator/create_python_api.py script.
"""Public API for tf.config.gpu namespace.
"""

from __future__ import print_function as _print_function

from tensorflow.python.framework.config import get_gpu_per_process_memory_fraction as get_per_process_memory_fraction
from tensorflow.python.framework.config import get_gpu_per_process_memory_growth as get_per_process_memory_growth
from tensorflow.python.framework.config import set_gpu_per_process_memory_fraction as set_per_process_memory_fraction
from tensorflow.python.framework.config import set_gpu_per_process_memory_growth as set_per_process_memory_growth

del _print_function
