# This file is MACHINE GENERATED! Do not edit.
# Generated by: tensorflow/python/tools/api/generator/create_python_api.py script.
"""Public API for tf.config.experimental namespace.
"""

from __future__ import print_function as _print_function

from tensorflow.python.framework.config import get_device_policy
from tensorflow.python.framework.config import get_synchronous_execution
from tensorflow.python.framework.config import set_device_policy
from tensorflow.python.framework.config import set_synchronous_execution

del _print_function
